"""Generated Content entity - Represents the output of a generation job."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, Optional
from uuid import UUID, uuid4

from ..value_objects import ContentType


@dataclass
class GeneratedContent:
    """
    Represents content generated by a job.
    
    Attributes:
        id: Unique identifier for the content
        job_id: ID of the job that generated this content
        content_url: URL where the content is stored
        content_type: Type of content (image, video, text)
        file_size: Size of the file in bytes
        file_format: File format (png, mp4, txt, etc.)
        width: Width in pixels (for images/videos)
        height: Height in pixels (for images/videos)
        duration: Duration in seconds (for videos)
        metadata: Additional metadata about the content
        created_at: When the content was created
        is_public: Whether the content is publicly accessible
        nsfw_score: NSFW detection score (0.0 - 1.0)
        is_moderated: Whether content has been moderated
    """
    
    # Required fields
    job_id: UUID
    content_url: str
    content_type: ContentType
    
    # Auto-generated fields
    id: UUID = field(default_factory=uuid4)
    created_at: datetime = field(default_factory=datetime.utcnow)
    
    # Optional fields
    file_size: Optional[int] = None
    file_format: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None
    duration: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    is_public: bool = False
    nsfw_score: Optional[float] = None
    is_moderated: bool = False
    
    def __post_init__(self) -> None:
        """Validate fields after initialization."""
        # Validate content URL
        if not self.content_url:
            raise ValueError("Content URL cannot be empty")
        
        # Set default file format if not provided
        if self.file_format is None:
            self.file_format = self.content_type.get_file_extension()
        
        # Validate dimensions
        if self.width is not None and self.width <= 0:
            raise ValueError("Width must be positive")
        
        if self.height is not None and self.height <= 0:
            raise ValueError("Height must be positive")
        
        # Validate duration
        if self.duration is not None and self.duration <= 0:
            raise ValueError("Duration must be positive")
        
        # Validate NSFW score
        if self.nsfw_score is not None and not (0.0 <= self.nsfw_score <= 1.0):
            raise ValueError("NSFW score must be between 0.0 and 1.0")
    
    def get_public_url(self, cdn_url: Optional[str] = None) -> str:
        """
        Get the public URL for the content.
        
        Args:
            cdn_url: Optional CDN URL to prepend
            
        Returns:
            Public URL for the content
        """
        if cdn_url:
            # Replace storage URL with CDN URL
            return self.content_url.replace("s3://", f"{cdn_url}/")
        return self.content_url
    
    def get_mime_type(self) -> str:
        """
        Get the MIME type for the content.
        
        Returns:
            MIME type string
        """
        return self.content_type.get_mime_type()
    
    def set_dimensions(self, width: int, height: int) -> None:
        """
        Set the dimensions of the content.
        
        Args:
            width: Width in pixels
            height: Height in pixels
        """
        if width <= 0 or height <= 0:
            raise ValueError("Dimensions must be positive")
        
        self.width = width
        self.height = height
    
    def set_duration(self, duration: float) -> None:
        """
        Set the duration of the content (for videos).
        
        Args:
            duration: Duration in seconds
        """
        if duration <= 0:
            raise ValueError("Duration must be positive")
        
        self.duration = duration
    
    def set_nsfw_score(self, score: float) -> None:
        """
        Set the NSFW detection score.
        
        Args:
            score: NSFW score (0.0 - 1.0)
        """
        if not (0.0 <= score <= 1.0):
            raise ValueError("NSFW score must be between 0.0 and 1.0")
        
        self.nsfw_score = score
    
    def is_nsfw(self, threshold: float = 0.7) -> bool:
        """
        Check if content is NSFW based on threshold.
        
        Args:
            threshold: NSFW threshold (default: 0.7)
            
        Returns:
            True if content is NSFW, False otherwise
        """
        if self.nsfw_score is None:
            return False
        
        return self.nsfw_score >= threshold
    
    def mark_as_moderated(self) -> None:
        """Mark content as moderated."""
        self.is_moderated = True
    
    def make_public(self) -> None:
        """Make content publicly accessible."""
        self.is_public = True
    
    def make_private(self) -> None:
        """Make content private."""
        self.is_public = False
    
    def add_metadata(self, key: str, value: Any) -> None:
        """
        Add metadata to the content.
        
        Args:
            key: Metadata key
            value: Metadata value
        """
        self.metadata[key] = value
    
    def get_metadata(self, key: str, default: Any = None) -> Any:
        """
        Get metadata value.
        
        Args:
            key: Metadata key
            default: Default value if key not found
            
        Returns:
            Metadata value or default
        """
        return self.metadata.get(key, default)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert entity to dictionary representation."""
        return {
            "id": str(self.id),
            "job_id": str(self.job_id),
            "content_url": self.content_url,
            "content_type": self.content_type.value,
            "file_size": self.file_size,
            "file_format": self.file_format,
            "width": self.width,
            "height": self.height,
            "duration": self.duration,
            "metadata": self.metadata,
            "created_at": self.created_at.isoformat(),
            "is_public": self.is_public,
            "nsfw_score": self.nsfw_score,
            "is_moderated": self.is_moderated,
        }

